name: Java CI with Maven

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      checks: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
          java-version: 22
          distribution: 'adopt'

#      - name: Run tests
#        run: mvn test
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Build and Run Tests
        run: mvn test --batch-mode --fail-at-end
      - name: Publish Test Report
        if: success() || failure()
        uses: ScaCap/action-surefire-report@v1.8.0

